name: dotNET using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: dotnet build testdotnetwebapi --configuration Release
      - name: ls
        working-directory: testdotnetwebapi/testdotnetwebapi
        run: ls
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        with:
          args: --file=testdotnetwebapi.sln
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
